language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t maguroid/docker-react-tutorial -f Dockerfile.dev .

script:
  - docker run -e CI=true maguroid/docker-react-tutorial npm run test
