language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t maguroid/docker-react-tutorial -f Dockerfile.dev .

script:
  - docker run -e CI=true maguroid/docker-react-tutorial npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-616860242390"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
